### ISSUE TITLE
custom proxy

### ISSUE THREAD

**Issue by ezzmay007** [zpelechova/instagram-miniactors#4]
Hi Zuzka, im using your instagram post scraper on apify and im trying to work out how to add some custom proxy URLs via the console, the official docs say
To use your own proxies with Apify Console, in your actor's Input and options tab, scroll down and open the Proxy and browser configuration section. Enter your proxy URLs and you're good to go.

then in your docs it says
You can also use proxies from other providers in the custom proxies fields (proxyUrls in the JSON settings).

can you please help me on how to get this working?

Thanks
Erin

**Comment by zpelechova** [comment]
Hi Erin, 
I created these actors to be super easy to use for non technical people (who often dont know what a proxy is) so I dont really want to add it, but it is really just running this actor: https://apify.com/jaroslavhejlek/instagram-scraper (where you can set up your own proxies). So you can either use that one or you can fork these and make your own private actor on Apify by just adding the proxy field to the input schema (and removing the proxy condition from main.js)
`        "proxy": {
            "title": "Proxy configuration",
            "type": "object",
            "description": "<strong>A proxy server is required to run this actor!</strong> Either use an Apify residential proxy, or provide your own proxy servers. Datacenter proxies will not work.",
            "prefill": {
                "useApifyProxy": true,
                "apifyProxyGroups": ["RESIDENTIAL"]
            },
            "editor": "proxy",
            "sectionCaption": "Proxy & browser configuration",
            "sectionDescription": "Select your proxy here. Use Residential for scrapping without login, but automatic for scraping with login! You can also change the maximum times the browser will retry requests and tell it how long to wait for the page to scroll."
        },
`
Fair warning - as Instagram changed the layout (again) and the data structure in APIs, the actors are not working very well at the moment and we are woking on fixing it.
